# Site settings
title: Fancy Footage Club
email: admin@fancyfootage.club
description: 'Cinema-quality footage for creative projects of every size'
baseurl: ""
dlurl: "https://s3.amazonaws.com/fancyfootageclips/loops/"
asseturl: "https://s3.amazonaws.com/fancyfootageclips/website/"
url: "" 

exclude: ['css/src', 'package.json', '/node_modules', 'gruntfile.js', 'npm-debug.log']

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values: 
      permalink: library/:year/:month/:title/

# Build settings
markdown: kramdown
sass_dir: css/_sass
